# Generated by Django 5.2.4 on 2025-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_practice_remove_book_number_remove_character_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(max_length=10),
        ),
    ]
