# Generated by Django 5.2.4 on 2025-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_practice_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
