# Generated by Django 5.2.4 on 2025-08-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
