# Generated by Django 5.2.4 on 2025-08-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_paper_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='date',
        ),
    ]
