# Generated by Django 5.2.4 on 2025-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_remove_paper_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='examination',
            field=models.CharField(default='MTE or ETE', max_length=100),
        ),
    ]
