# Generated by Django 5.2.4 on 2025-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_paper_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='examination',
            field=models.CharField(max_length=100),
        ),
    ]
