# Generated by Django 5.2.4 on 2025-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_alter_paper_examination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='description',
        ),
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(default='paper.pdf', upload_to='papers/'),
        ),
    ]
